// <auto-generated />
using System;
using EfCoreTpc.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EfCoreTpc.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260201130816_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.HasSequence("EmployeeSequence");

            modelBuilder.Entity("EfCoreTpc.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValueSql("nextval('\"EmployeeSequence\"')");

                    NpgsqlPropertyBuilderExtensions.UseSequence(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.UseTpcMappingStrategy();
                });

            modelBuilder.Entity("EfCoreTpc.Models.Contractor", b =>
                {
                    b.HasBaseType("EfCoreTpc.Models.Employee");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Contractors");
                });

            modelBuilder.Entity("EfCoreTpc.Models.FullTimeEmployee", b =>
                {
                    b.HasBaseType("EfCoreTpc.Models.Employee");

                    b.Property<decimal>("AnnualBonus")
                        .HasColumnType("numeric");

                    b.Property<int>("VacationDays")
                        .HasColumnType("integer");

                    b.ToTable("FullTimeEmployees");
                });

            modelBuilder.Entity("EfCoreTpc.Models.PartTimeEmployee", b =>
                {
                    b.HasBaseType("EfCoreTpc.Models.Employee");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("integer");

                    b.ToTable("PartTimeEmployees");
                });
#pragma warning restore 612, 618
        }
    }
}
