// <auto-generated />
using System;
using EfCoreTpt.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EfCoreTpt.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260201131210_InitialDb")]
    partial class InitialDb
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EfCoreTph.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("EfCoreTph.Models.Contractor", b =>
                {
                    b.HasBaseType("EfCoreTph.Models.Employee");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.ToTable("Contractors", (string)null);
                });

            modelBuilder.Entity("EfCoreTph.Models.FullTimeEmployee", b =>
                {
                    b.HasBaseType("EfCoreTph.Models.Employee");

                    b.Property<decimal>("AnnualBonus")
                        .HasColumnType("numeric");

                    b.Property<int>("VacationDays")
                        .HasColumnType("integer");

                    b.ToTable("FullTimeEmployees", (string)null);
                });

            modelBuilder.Entity("EfCoreTph.Models.PartTimeEmployee", b =>
                {
                    b.HasBaseType("EfCoreTph.Models.Employee");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("integer");

                    b.ToTable("PartTimeEmployees", (string)null);
                });

            modelBuilder.Entity("EfCoreTph.Models.Contractor", b =>
                {
                    b.HasOne("EfCoreTph.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("EfCoreTph.Models.Contractor", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EfCoreTph.Models.FullTimeEmployee", b =>
                {
                    b.HasOne("EfCoreTph.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("EfCoreTph.Models.FullTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EfCoreTph.Models.PartTimeEmployee", b =>
                {
                    b.HasOne("EfCoreTph.Models.Employee", null)
                        .WithOne()
                        .HasForeignKey("EfCoreTph.Models.PartTimeEmployee", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
