// <auto-generated />
using System;
using EfCoreTph.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EfCoreTph.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EfCoreTph.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("BaseSalary")
                        .HasColumnType("numeric");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte>("EmployeeType")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("HireDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasDiscriminator<byte>("EmployeeType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("EfCoreTph.Models.Contractor", b =>
                {
                    b.HasBaseType("EfCoreTph.Models.Employee");

                    b.Property<string>("AgencyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("ContractEndDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasDiscriminator().HasValue((byte)3);
                });

            modelBuilder.Entity("EfCoreTph.Models.FullTimeEmployee", b =>
                {
                    b.HasBaseType("EfCoreTph.Models.Employee");

                    b.Property<decimal>("AnnualBonus")
                        .HasColumnType("numeric");

                    b.Property<int>("VacationDays")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue((byte)1);
                });

            modelBuilder.Entity("EfCoreTph.Models.PartTimeEmployee", b =>
                {
                    b.HasBaseType("EfCoreTph.Models.Employee");

                    b.Property<decimal>("HourlyRate")
                        .HasColumnType("numeric");

                    b.Property<int>("WeeklyHours")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue((byte)2);
                });
#pragma warning restore 612, 618
        }
    }
}
